# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ed34c0d912d7ea3ec05cf859df8d841a66e8f4df27c92ee8a3e6e3a0eb2d53e9911874299f641da24d91eff6513ff08a49895527ced0541ab52cf4aa7787937

test:
  secret_key_base: 28099805fabc9ba9d4570917c68a4fc86f4fa62b4357bd4d106f0d4339e5406df6febef711552ba44fb0343c8c0705ebd4e7a8b3bbe1a831acda53e148845ee9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
